import React, { useContext, useEffect, useState } from 'react'
import Typography from '@mui/material/Typography'
import Paper from '@mui/material/Paper'
import List from '@mui/material/List'
import ListItem from '@mui/material/ListItem'
import ListItemAvatar from '@mui/material/ListItemAvatar'
import ListItemText from '@mui/material/ListItemText'
import ListSubheader from '@mui/material/ListSubheader'
import Avatar from '@mui/material/Avatar'

import AppService from '../../service/AppService'
import styles from './Inbox.module.css'

import { ModalUI } from '../ModalUI/ModalUI'
import { useParams } from 'react-router-dom'
import { AuthContext } from '../../contexts/AuthContext'

const messages = [
  {
    id: 1,
    primary: 'Mr. Secret',
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 2,
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    id: 3,
    primary: 'Recipe to try',
    secondary:
      'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
  {
    id: 4,
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    id: 6,
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 7,
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
]

export const Inbox = () => {
  const { user } = useContext(AuthContext)
  const [modalOpen, setModalOpen] = useState(false)
  const [texts, setTexts] = useState([])

  useEffect(() => {
    async function getAllTextsForThisUser() {
      const res = await AppService.getInbox(user._id)
      setTexts(res.data.text)
    }
    getAllTextsForThisUser()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  return (
    <div className={styles.container}>
      <Paper square sx={{ pb: '50px' }}>
        <Typography
          variant="h5"
          gutterBottom
          component="div"
          sx={{ p: 2, pb: 0 }}
        >
          Inbox
        </Typography>
        <List sx={{ mb: 2 }}>
          {texts &&
            texts.map(({ _id, text }, index) => (
              <React.Fragment key={_id}>
                {index === 1 && (
                  <ListSubheader sx={{ bgcolor: 'background.paper' }}>
                    Today
                  </ListSubheader>
                )}

                {index === 3 && (
                  <ListSubheader sx={{ bgcolor: 'background.paper' }}>
                    Yesterday
                  </ListSubheader>
                )}

                <ListItem
                  button
                  onClick={() => {
                    setModalOpen(!modalOpen)
                  }}
                >
                  <ListItemAvatar>
                    {/* <Avatar alt="Profile Picture" src={person} /> */}
                  </ListItemAvatar>
                  <ListItemText primary="Nick Name" secondary={text} />
                </ListItem>
                <ModalUI
                  modalOpen={modalOpen}
                  setModalOpen={setModalOpen}
                  data={{nickName: 'Tanbir', text}}
                />
              </React.Fragment>
            ))}
        </List>
      </Paper>
    </div>
  )
}
